[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."post"]
  included_files = []

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200

[[redirects]]
  from = "/api/trend"
  to = "/.netlify/functions/trend"
  status = 200

[[redirects]]
  from = "/api/advise"
  to = "/.netlify/functions/advise"
  status = 200

[[redirects]]
  from = "/api/instagram"
  to = "/.netlify/functions/instagram"
  status = 200

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200
